package orientacaoAObjetos.interfaceEPolimorfismo;

import orientacaoAObjetos.interfaceEPolimorfismo.DimensaoSuperficial;
import orientacaoAObjetos.interfaceEPolimorfismo.DimensaoVolumetrica;
import orientacaoAObjetos.interfaceEPolimorfismo.FiguraGeometrica;

public abstract class Figura3D extends FiguraGeometrica implements DimensaoSuperficial, DimensaoVolumetrica {

}
